# kubernetes-cluster-role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-service-account
    namespace: default  # Update this if you want to use a specific namespace
roleRef:
  kind: ClusterRole
  name: kubernetes-cluster-role
  apiGroup: rbac.authorization.k8s.io
