# Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy only the requirements file into the container at /app
COPY ./requirements.txt /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY ./k8s_pod_status_checker.py /app

# Run the Python script when the container starts
CMD [ "python", "k8s_pod_status_checker.py" ]